import MediaByteCache

public typealias CacheKeyStore = MediaByteCache.CacheKeyStore
public typealias KeychainCacheKeyStore = MediaByteCache.KeychainCacheKeyStore
public typealias SecureBlobCipher = MediaByteCache.SecureBlobCipher
public typealias SecureBlobCipherError = MediaByteCache.SecureBlobCipherError
public typealias ThumbnailCache = MediaByteCache.ThumbnailCache
public typealias ThumbnailCacheConfiguration = MediaByteCache.ThumbnailCacheConfiguration
